from django.urls import path
from . import views
from .views.student_assignment_compat import student_assignment_info as student_assignment_info_compat


urlpatterns = [

    # 공통
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_view, name="logout"),

    # 학생
    path("", views.student_home, name="student_home"),
    path("team-info/", views.student_team_info, name="student_team_info"),
    path("assignment-info/", student_assignment_info_compat, name="student_assignment_info"),
    path("attachments/assignments/<int:assignment_id>/download/", views.assignment_attachment_download, name="assignment_attachment_download"),
    path("attachments/submissions/<int:submission_id>/download/", views.submission_attachment_download, name="submission_attachment_download"),
    path("attachments/student-submissions/<int:submission_id>/download/", views.student_submission_attachment_download, name="student_submission_attachment_download"),
    path("team-evaluation/", views.student_team_evaluation, name="student_team_evaluation"),
    path("personal-evaluation/", views.student_personal_evaluation, name="student_personal_evaluation"),
    path("evaluation-status/", views.student_evaluation_status, name="student_evaluation_status"),
    path("results/", views.student_results, name="student_results"),
    path("self-review/", views.student_self_review, name="student_self_review"),
    path("feedback/", views.student_feedback, name="student_feedback"),
    path("feedback/<int:feedback_id>/read/", views.student_feedback_read, name="student_feedback_read"),
    path("notifications/", views.student_notifications, name="student_notifications"),
    path("messages/", views.student_messages, name="student_messages"),
    path("messages/<int:message_id>/read/", views.student_message_read, name="student_message_read"),
    path("announcements/<int:announcement_id>/read/", views.student_announcement_read, name="student_announcement_read"),
    path("hr-tasks/", views.student_hr_tasks, name="student_hr_tasks"),
    path("hr-tasks/<int:task_id>/attachment/download/", views.hr_task_attachment_download, name="hr_task_attachment_download"),
    path("hr-tasks/<int:task_id>/steps/<int:step_id>/toggle/", views.student_hr_task_step_toggle, name="student_hr_task_step_toggle"),
    path("hr-tasks/<int:task_id>/submit/", views.student_hr_task_submit, name="student_hr_task_submit"),
    path("profile/", views.student_profile, name="student_profile"),

    # 관리자
    path("management/", views.admin_dashboard, name="admin_dashboard"),
    path("management/announcements/", views.admin_announcements, name="admin_announcements"),
    path("management/messages/", views.admin_messages, name="admin_messages"),
    path("management/activity-logs/", views.admin_activity_logs, name="admin_activity_logs"),
    path("management/attendance/", views.admin_attendance, name="admin_attendance"),
    path("management/skills/", views.admin_skills, name="admin_skills"),
    path("management/skills/create/", views.admin_skill_create, name="admin_skill_create"),
    path("management/skills/sync/", views.admin_skill_sync_all, name="admin_skill_sync_all"),
    path("management/skills/<int:skill_id>/update/", views.admin_skill_update, name="admin_skill_update"),
    path("management/skills/<int:skill_id>/delete/", views.admin_skill_delete, name="admin_skill_delete"),
    path("management/students/", views.admin_students, name="admin_students"),
    path("management/students/skills/bulk-save/", views.admin_students_bulk_skill_save, name="admin_students_bulk_skill_save"),
    path("management/students/excel-upload/", views.admin_students_excel_upload, name="admin_students_excel_upload"),
    path("management/students/excel-export/", views.admin_students_excel_export, name="admin_students_excel_export"),
    path("management/students/create/", views.admin_student_create, name="admin_student_create"),
    path("management/students/<int:student_id>/update/", views.admin_student_update, name="admin_student_update"),
    path("management/students/messages/bulk/", views.admin_students_bulk_message_send, name="admin_students_bulk_message_send"),
    path("management/students/<int:student_id>/message/", views.admin_student_message_send, name="admin_student_message_send"),
    path("management/students/<int:student_id>/", views.admin_student_detail, name="admin_student_detail"),
    path("management/students/<int:student_id>/skills/save/", views.admin_student_skill_save, name="admin_student_skill_save"),
    path("management/students/<int:student_id>/skills/<int:profile_id>/delete/", views.admin_student_skill_delete, name="admin_student_skill_delete"),
    path("management/students/<int:student_id>/comments/save/", views.admin_student_comment_save, name="admin_student_comment_save"),
    path("management/students/<int:student_id>/comments/<int:comment_id>/delete/", views.admin_student_comment_delete, name="admin_student_comment_delete"),
    path("management/students/<int:student_id>/reset-password/", views.admin_student_reset_password, name="admin_student_reset_password"),
    path("management/students/<int:student_id>/toggle-active/", views.admin_student_toggle_active, name="admin_student_toggle_active"),
    path("management/students/<int:student_id>/delete/", views.admin_student_delete, name="admin_student_delete"),
    path("management/operations/", views.admin_operations, name="admin_operations"),
    path("management/rounds/", views.admin_rounds, name="admin_rounds"),
    path("management/rounds/<int:round_id>/", views.admin_round_detail, name="admin_round_detail"),
    path("management/rounds/create/", views.admin_round_create, name="admin_round_create"),
    path("management/rounds/<int:round_id>/update/", views.admin_round_update, name="admin_round_update"),
    path("management/rounds/<int:round_id>/delete/", views.admin_round_delete, name="admin_round_delete"),
    path("management/rounds/<int:round_id>/apply-templates/", views.admin_round_apply_templates, name="admin_round_apply_templates"),
    path("management/rounds/<int:round_id>/<str:action>/", views.admin_round_action, name="admin_round_action"),
    path("management/hr/", views.admin_hr_dashboard, name="admin_hr_dashboard"),
    path("management/hr-tasks/", views.admin_hr_tasks, name="admin_hr_tasks"),
    path("management/hr-tasks/create/", views.admin_hr_task_save, name="admin_hr_task_create"),
    path("management/hr-tasks/<int:task_id>/update/", views.admin_hr_task_save, name="admin_hr_task_update"),
    path("management/hr-tasks/<int:task_id>/delete/", views.admin_hr_task_delete, name="admin_hr_task_delete"),
    path("management/hr-tasks/<int:task_id>/steps/add/", views.admin_hr_task_step_add, name="admin_hr_task_step_add"),
    path("management/hr-tasks/<int:task_id>/steps/<int:step_id>/update/", views.admin_hr_task_step_update, name="admin_hr_task_step_update"),
    path("management/hr-tasks/<int:task_id>/steps/<int:step_id>/delete/", views.admin_hr_task_step_delete, name="admin_hr_task_step_delete"),
    path("management/hr-tasks/<int:task_id>/revision/", views.admin_hr_task_request_revision, name="admin_hr_task_request_revision"),
    path("management/hr-tasks/<int:task_id>/evaluate/", views.admin_hr_task_evaluate, name="admin_hr_task_evaluate"),
    path("management/hr-tasks/<int:task_id>/recommend/<int:student_id>/assign/", views.admin_hr_task_assign_recommended, name="admin_hr_task_assign_recommended"),
    path("management/assignments/", views.admin_assignments, name="admin_assignments"),
    path("management/assignments/create/", views.admin_assignment_create, name="admin_assignment_create"),
    path("management/assignments/<int:assignment_id>/update/", views.admin_assignment_update, name="admin_assignment_update"),
    path("management/assignments/<int:assignment_id>/delete/", views.admin_assignment_delete, name="admin_assignment_delete"),
    path("management/submissions/<int:submission_id>/comment/", views.admin_submission_comment, name="admin_submission_comment"),
    path("management/teams/", views.admin_teams, name="admin_teams"),
    path("management/teams/export/", views.admin_teams_excel_export, name="admin_teams_excel_export"),
    path("management/teams/create/", views.admin_team_create, name="admin_team_create"),
    path("management/teams/<int:team_id>/update/", views.admin_team_update, name="admin_team_update"),
    path("management/teams/<int:team_id>/delete/", views.admin_team_delete, name="admin_team_delete"),
    path("management/team-assignment/", views.admin_team_assignment, name="admin_team_assignment"),
    path("management/team-assignment/manual/assign/", views.admin_manual_assign, name="admin_manual_assign"),
    path("management/team-assignment/manual/unassign/", views.admin_manual_unassign, name="admin_manual_unassign"),
    path("management/team-assignment/member/<int:membership_id>/role/", views.admin_team_member_role_update, name="admin_team_member_role_update"),
    path("management/team-assignment/dissolve/", views.admin_team_dissolve_all, name="admin_team_dissolve_all"),
    path("management/team-assignment/auto/preview/", views.admin_auto_preview, name="admin_auto_preview"),
    path("management/team-assignment/auto/confirm/", views.admin_auto_confirm, name="admin_auto_confirm"),
    path(
        "management/evaluation-templates/",
        views.admin_evaluation_templates,
        name="admin_evaluation_templates",
    ),
    path("management/evaluation-templates/create/", views.admin_evaluation_template_create, name="admin_evaluation_template_create"),
    path("management/evaluation-templates/<int:template_id>/update/", views.admin_evaluation_template_update, name="admin_evaluation_template_update"),
    path("management/evaluation-templates/<int:template_id>/toggle/", views.admin_evaluation_template_toggle, name="admin_evaluation_template_toggle"),
    path("management/evaluation-templates/<int:template_id>/delete/", views.admin_evaluation_template_delete, name="admin_evaluation_template_delete"),
    path("management/evaluation-templates/<int:template_id>/criteria/create/", views.admin_evaluation_criterion_create, name="admin_evaluation_criterion_create"),
    path("management/evaluation-criteria/<int:criterion_id>/update/", views.admin_evaluation_criterion_update, name="admin_evaluation_criterion_update"),
    path("management/evaluation-criteria/<int:criterion_id>/delete/", views.admin_evaluation_criterion_delete, name="admin_evaluation_criterion_delete"),
    path("management/evaluation-criteria/<int:criterion_id>/move/<str:direction>/", views.admin_evaluation_criterion_move, name="admin_evaluation_criterion_move"),
    path("management/evaluation-templates/<int:template_id>/criteria/reorder/", views.admin_evaluation_criteria_reorder, name="admin_evaluation_criteria_reorder"),

    path(
        "management/evaluation-results/",
        views.admin_evaluation_results,
        name="admin_evaluation_results",
    ),
    path(
        "management/evaluation-results/missing/",
        views.admin_missing_evaluations,
        name="admin_missing_evaluations",
    ),
    path("management/evaluation-results/export/", views.admin_evaluation_results_excel_export, name="admin_evaluation_results_excel_export"),
    path("management/evaluation-results/weights/", views.admin_result_weights_save, name="admin_result_weights_save"),
    path("management/evaluation-results/<int:result_id>/adjust/", views.admin_student_result_adjust, name="admin_student_result_adjust"),
    path("management/team-scores/", views.admin_team_scores, name="admin_team_scores"),
    path(
        "management/personal-scores/",
        views.admin_personal_scores,
        name="admin_personal_scores",
    ),
    path("management/rankings/", views.admin_rankings, name="admin_rankings"),
    path(
        "management/result-settings/",
        views.admin_result_settings,
        name="admin_result_settings",
    ),
    path(
        "management/seed/",
        views.admin_seed_management,
        name="admin_seed_management",
    ),

    path("management/data/", views.admin_data_management, name="admin_data_management"),
    path("management/data/media-cleanup/", views.admin_media_cleanup, name="admin_media_cleanup"),
    path("management/data/backup/", views.admin_data_backup_download, name="admin_data_backup_download"),
    path("management/data/restore/", views.admin_data_restore, name="admin_data_restore"),
]
