# Generated by Django 6.1 on 2026-08-13 06:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('in_progress', '진행 중'), ('ended', '종료')], default='scheduled', max_length=20)),
                ('is_reopened', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='assignments/')),
                ('evaluation_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='dashboard.evaluationround')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('evaluation_type', models.CharField(choices=[('team', '팀 평가'), ('personal', '개인 평가')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_templates', to='dashboard.evaluationround')),
            ],
            options={
                'ordering': ['evaluation_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_score', models.PositiveSmallIntegerField(default=5)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='dashboard.evaluationtemplate')),
            ],
            options={
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultPublishSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('show_team_first_place', models.BooleanField(default=True)),
                ('show_all_team_ranks', models.BooleanField(default=True)),
                ('show_personal_score', models.BooleanField(default=True)),
                ('show_overall_rank', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=True)),
                ('evaluation_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_setting', to='dashboard.evaluationround')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_evaluations', to='dashboard.evaluationround')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_evaluations_given', to='dashboard.student')),
                ('target_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_evaluations_received', to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('personal_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_excluded', models.BooleanField(default=False)),
                ('evaluation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='dashboard.evaluationround')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.evaluationround')),
            ],
            options={
                'ordering': ['evaluation_round', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to='dashboard.evaluationround')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations_given', to='dashboard.student')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations_received', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_scores', to='dashboard.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dashboard.teamevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='dashboard.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dashboard.team')),
            ],
            options={
                'ordering': ['team', 'student'],
            },
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_excluded', models.BooleanField(default=False)),
                ('evaluation_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='dashboard.evaluationround')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.team')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_scores', to='dashboard.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dashboard.personalevaluation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_personal_criterion_score')],
            },
        ),
        migrations.AddConstraint(
            model_name='personalevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation_round', 'evaluator', 'target_student'), name='unique_personal_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='studentresult',
            constraint=models.UniqueConstraint(fields=('evaluation_round', 'student'), name='unique_student_result'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('evaluation_round', 'name'), name='unique_team_name_per_round'),
        ),
        migrations.AddConstraint(
            model_name='teamevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation_round', 'evaluator', 'target_team'), name='unique_team_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='teamevaluationscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_team_criterion_score'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'student'), name='unique_student_membership_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teamresult',
            constraint=models.UniqueConstraint(fields=('evaluation_round', 'team'), name='unique_team_result'),
        ),
    ]
