# Generated by Django 6.1 on 2026-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_evaluationtemplate_is_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['evaluation_round', 'assignment_type', 'id']},
        ),
        migrations.RemoveField(
            model_name='evaluationtemplate',
            name='is_snapshot',
        ),
        migrations.AddField(
            model_name='team',
            name='is_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, verbose_name='소속'),
        ),
    ]
